.PHONY: clean cleaner

all:
	python3 ../support/tutorial_tools/notebook/process_notebook.py valgrind

clean:
	rm -f valgrind.md Doxyfile
	rm -rf html

cleaner:
	rm -f valgrind.ipynb valgrind.md Doxyfile
	rm -rf html
